const ExistButtons= {
    undo:"undo",
    redo:"redo",
    font:"font",
    fontSize:"fontSize",
    formatBlock:"formatBlock",
    paragraphStyle:"paragraphStyle",
    blockquote:"blockquote",
    bold:"bold",
    underline:"underline",
    italic:"italic",
    strike:"strike",
    subscript:"subscript",
    superscript:"superscript",
    fontColor:"fontColor",
    hiliteColor:"hiliteColor",
    textStyle:"textStyle",
    removeFormat:"removeFormat",
    outdent:"outdent",
    indent:"indent",
    align:"align",
    horizontalRule:"horizontalRule",
    list:"list",
    lineHeight:"lineHeight",
    table:"table",
    link:"link",
    image:"image",
    video:"video",
    audio:"audio",
    // math:"math",
    imageGallery:"imageGallery",
    fullScreen:"fullScreen",
    showBlocks:"showBlocks",
    codeView:"codeView",
    preview:"preview",
    print:"print",
    save:"save",
    template:"template",
    
};
export const MySetButtons:any[]=
[
   [ExistButtons.formatBlock] ,
   [ExistButtons.bold,ExistButtons.italic,ExistButtons.removeFormat] ,
   [ExistButtons.font,ExistButtons.hiliteColor,ExistButtons.fontColor] ,
   [':p-More Paragraph-default.more_paragraph', ExistButtons.list, ExistButtons.align,ExistButtons.indent,ExistButtons.outdent],
   [ExistButtons.table] ,
   [ExistButtons.link,ExistButtons.image,ExistButtons.video] ,
   ['-center', ExistButtons.fullScreen,ExistButtons.codeView] ,
   ['-right', ExistButtons.undo,ExistButtons.redo] ,
]
